server:
    port: 8886
    max-http-header-size: 100000

spring:
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    application:
        name: now
    cache:
        jcache:
            config: classpath:ehcache3.xml
guozheng12:
    name: guozheng
    age: 18


